// // app/layout.js

// "use client";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import Navbar from "@/components/Navbar";
// import Footer from "@/components/Footer"; // Import Footer
// import { ThemeProvider } from "@/components/theme-provider";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "AnkitBlogs",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en" className="scroll-p-20 scroll-smooth">
//       <body className={inter.className}>
//         <ThemeProvider
//           attribute="class"
//           defaultTheme="system"
//           enableSystem
//           disableTransitionOnChange
//         >
//           <Navbar />
//           {children}
//           <Footer />  {/* Add Footer here */}
//         </ThemeProvider>
//       </body>
//     </html>
//   );
// }



// "use client"; // Add this line only if necessary, e.g., if you're using `useState` or `useEffect` in this file.

// import { Inter } from "next/font/google";
// import "./globals.css";
// import Navbar from "@/components/Navbar";
// import Footer from "@/components/Footer";
// import { ThemeProvider } from "@/components/theme-provider";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "AnkitBlogs",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en" className="scroll-p-20 scroll-smooth">
//       <body className={inter.className}>
//         <ThemeProvider
//           attribute="class"
//           defaultTheme="system"
//           enableSystem
//           disableTransitionOnChange
//         >
//           <Navbar />
//           {children}
//           <Footer /> {/* Footer added here */}
//         </ThemeProvider>
//       </body>
//     </html>
//   );
// }




// "use client" directive is not needed here for Server Components

import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ThemeProvider } from "@/components/theme-provider";  // Import your ThemeProvider

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "AnkitBlogs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-p-20 scroll-smooth dark">
      <body className={inter.className}>
        {/* Wrapping the app with ThemeProvider */}
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Navbar />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
